export const AppRouters = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register-company",
  INVITE_ACCEPT: "/invite/accept",
  DASHBOARD: "/dashboard",
  PROFILE: "/profile",
  FORBIDDEN: "/403",
  // Admin
  ADMIN_DEPARTMENTS: "/admin/departments",
  ADMIN_USERS: "/admin/users",
  ADMIN_ROLES: "/admin/roles",
  ADMIN_KNOWLEDGE_BASE: "/admin/knowledge-base",
  // Settings
  SETTINGS_NOTIFICATIONS: "/settings/notifications",
  // Onboarding
  ONBOARDING_TEMPLATES: "/onboarding/templates",
  ONBOARDING_TEMPLATES_NEW: "/onboarding/templates/new",
  ONBOARDING_EMPLOYEES: "/onboarding/employees",
  ONBOARDING_EMPLOYEES_NEW: "/onboarding/employees/new",
  ONBOARDING_TASKS: "/onboarding/tasks",
  ONBOARDING_AUTOMATION: "/onboarding/automation",
  // Documents
  DOCUMENTS: "/documents",
  DOCUMENTS_ACKNOWLEDGMENTS: "/documents/acknowledgments",
  // Surveys
  SURVEYS_TEMPLATES: "/surveys/templates",
  SURVEYS_TEMPLATES_NEW: "/surveys/templates/new",
  SURVEYS_SEND: "/surveys/send",
  SURVEYS_INBOX: "/surveys/inbox",
  SURVEYS_REPORTS: "/surveys/reports",
  // Chatbot
  CHATBOT: "/chatbot",
  // Billing
  BILLING_PLAN: "/billing/plan",
  BILLING_USAGE: "/billing/usage",
  BILLING_INVOICES: "/billing/invoices",
  BILLING_PAYMENT: "/billing/payment",
  // Platform
  PLATFORM_TENANTS: "/platform/tenants",
  PLATFORM_PLANS: "/platform/plans",
  PLATFORM_SUBSCRIPTIONS: "/platform/subscriptions",
  PLATFORM_USAGE: "/platform/usage",
  PLATFORM_FINANCE: "/platform/finance",
  PLATFORM_DUNNING: "/platform/dunning",
  PLATFORM_INVOICES: "/platform/invoices",
  PLATFORM_PAYMENTS: "/platform/payments",
  PLATFORM_EMAIL_LOGS: "/platform/email-logs",
} as const;

export type AppRouter = (typeof AppRouters)[keyof typeof AppRouters];
