export interface IAttendanceData {
    id: string;
    tenantId: string;
    employeeId: string;
    employeeName?: string;
    workDate: string;
    status: string;
    note?: string;
    isAutoGenerated: boolean;
    created: string;
    createdBy?: string;
    createdByName?: string;
    lastModified?: string;
    lastModifiedBy?: string;
    lastModifiedByName?: string;
}

export interface IAddEditAttendance {
    id?: string;
    employeeId: string;
    workDate: string;
    status: string;
    note?: string;
}

export interface IAttendanceSummary {
    employeeId?: string;
    employeeName?: string;
    month: string;
    totalDays: number;
    presentDays: number;
    absentDays: number;
    lateDays: number;
    leaveDays: number;
    attendanceRate: number;
}

export interface IAutoGenerateAttendance {
    month?: string;
    tenantId?: string;
    employeeId?: string;
}
