export * from './dashboard';
export * from './global';
export * from './layout';
export * from './notification';
export * from './order';
export * from './permission';
export * from './router';

export const ERROR_CODE = {
    // Quotation error codes
    INVALID_QUOTATION_APPROVER: 'QUT_ERR_011',
    CUSTOMER_IS_USED: 'CUS_ERR_007',
    DUPLICATED_CUSTOMER_PHONE: 'CUS_ERR_006',

    CHANGE_PASSWORD_FAILED: 'USE_ERR_006',
    INVALID_LOGIN: 'COM_ERR_000',

    // Category error code
    CATEGORY_DUPLICATE_CODE: 'CAT_ERR_006',

    // Product error codes
    PRODUCT_GROUP_IS_USED: 'PRG_ERR_007',
    PRODUCT_TYPE_IS_USED: 'PRT_ERR_007',
    PRODUCT_UNIT_IS_USED: 'PRU_ERR_007',
    PRODUCT_IS_USED: 'PRO_ERR_006',
    PRODUCT_DUPLICATE_CODE: 'PRO_ERR_008',
    // Supplier Type error code
    SUPPLIER_TYPE_IS_USED: 'SUT_ERR_007',

    // Customer Type error code
    CUSTOMER_TYPE_IS_USED: 'CUT_ERR_007',

    // User error code
    USER_DUPLICATE_EMAIL: 'USE_ERR_007',
    USER_DUPLICATE_USERNAME: 'USE_ERR_008',
    USER_DUPLICATE_PHONE: 'USE_ERR_009',

    // Supplier error code
    SUPPLIER_DUPLICATE_PHONE: 'SUP_ERR_006',

    // Role group error code
    ROLE_GROUP_IS_USED: 'ROG_ERR_007',
    // Payment slip error code
    PAYMENT_SLIP_IS_PAID: 'PMS_ERR_006',

    // Purchase order error code
    PURCHASE_ORDER_INSUFFICIENT_STOCK: 'PRO_ERR_007',

    // Export error code
    EXPORT_ORDER_FAILED: 'REP_ERR_002',
    EXPORT_INVOICE_FAILED: 'REP_ERR_003',
    EXPORT_NO_DATA: 'REP_ERR_004',
    EXPORT_PAYMENTSLIP_FAILED: 'REP_ERR_005',
    EXPORT_DEBT_FAILED: 'REP_ERR_006',
    EXPORT_DEBT_TRACKING: 'REP_ERR_007',

    //Paymentfund
    PAYMENT_FUND_IS_DUPLICATED: 'PAF_ERR_006',
    PAYMENT_FUND_IS_USED: 'EXT_ERR_009',
    //Expenses type
    EXPENSES_TYPE_DUPLICATE_CODE: 'EXT_ERR_006',
    EXPENSES_TYPE_IS_USED: 'EXT_ERR_009',

    //Import
    IMPORT_CANNOT_IMPORT_DATA: 'IMP_ERR_001',
    IMPORT_PRODUCTS_FAILED: 'IMP_ERR_002',
    IMPORT_INVALID_DATA: 'IMP_ERR_003',
    IMPORT_INVALID_FORMAT: 'IMP_ERR_004',
    IMPORT_INVALID_ID: 'IMP_ERR_005',
    IMPORT_INVALID_PRODUCT_UNIT_ID: 'IMP_ERR_006',
    IMPORT_INVALID_PRODUCT_TYPE_ID: 'IMP_ERR_007',
    IMPORT_INVALID_PRODUCT_GROUP_ID: 'IMP_ERR_008',
    IMPORT_INVALID_SUPPLIER_ID: 'IMP_ERR_009',
    IMPORT_NO_DATA: 'IMP_ERR_010',
    IMPORT_DUPLICATE_CODE: 'IMP_ERR_011',
};
